#!/bin/bash
LOCAL_DIR=$(git rev-parse --show-toplevel)
LOCAL_DIR=${LOCAL_DIR:-.}
cd $LOCAL_DIR

# Define tab character to get around sed limitation
TAB=$'\t'

# File References
README="$LOCAL_DIR/README.md"
TODO="$LOCAL_DIR/TODO.md"
SRC="$LOCAL_DIR/js/app"

# Clear the contents from TO DO to the end of file and prepare for appending
sed -i "" -e '/##\ TODO\ ##/,$ d' $README 2> /dev/null

######## TO DO #########
echo "## TODO ##" > $TODO
find "${SRC}" -type f -exec grep -H 'TODO:' {} \; 2> /dev/null | grep -v -e TODO.md -e README.md -e pre-commit | awk '{for (i=1; i<=NF-1; i++) $i = $(i+1); NF-=1; print}' | sed -e "s/.*TODO:[ ${TAB}]*//" | sed -e "s/^/- /" >> $TODO 2> /dev/null
echo "" >> $TODO

######## README ###########
cat $TODO >> $README

######## UPDATE GIT ###########
git add $TODO
git add $README

