#!/bin/bash
LOCAL_DIR=$(git rev-parse --show-toplevel)
LOCAL_DIR=${LOCAL_DIR:-.}
cd $LOCAL_DIR

# Define tab character to get around sed limitation
TAB=$'\t'

# File References
README="$LOCAL_DIR/README.md"
TODO="$LOCAL_DIR/TODO.md"
SRC="$LOCAL_DIR/js/ap"
